#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged

npx concurrently \
  --kill-others-on-fail \
  --prefix "[{name}]" \
  --names "typechecks,build" \
   --prefix-colors "bgRed.bold.white,bgGreen.bold.white,bgBlue.bold.white,bgMagenta.bold.white" \
    "npm run typechecks" \
    "npm run build" \
